name: 更新 CloudflareCIDRlist/CloudflareCIDR.list
permissions:
  contents: write

on:
  schedule:
    - cron: '35 2 * * *'  
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requests library
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download File
      run: python CloudflareCIDR-main.py  # 这里 CloudflareCIDR-main.py 处理文件

    - name: Check for changes and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .

        # 检查是否有变更
        if git diff --cached --quiet; then
          echo "没有文件变更，跳过提交"
        else
          echo "检测到文件变更，开始提交"
          git commit -m "Downloaded file on $(date '+%Y/%m/%d %H:%M:%S')"
          # 使用 actions/checkout@v3 默认保留的凭证（GITHUB_TOKEN）进行推送
          git pull --rebase origin main
          git push
          echo "提交完成"
        fi
